# Reimagine

Our purpose today is to spot things that could help your workflow. The ideas is to reuse what works (for you and others), and ease off what doesn’t work


## What resonates for you from last week?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.1--->

*Revisit what was top-of-mind from last week. What else has emerged? What patterns, if any, are coming up for you?*
Last week getting old workflows cleaned up and published along with figure out how to collaborate on work flows more effectively and navigate between different platforms and different organizations were top of mine. Another theme was finding was to speed up repetitive tasks like uploading raster files to Google Earth Engine. Another place that feels clunky is how I save and store different versions of data files. In past projects I have ended up with a bunch of versions of the same data file. I know that there are options to store versions of data files similar to code like with the large file service, but some of my data files are large so I am concerned about storage in GitHub because I only have the free account for my personal GitHub.

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::

## Where within your workflow seems like a good place to start iterating?
One good place to start iterating is on how I am storing, and collaborating on my code and data. I asked two different groups about creating GitHub or GitLab projects where we could start doing project management together for some of our work.
I'm also motivated to work on cleaning up and making some of my past workflows public.
::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What stands out about that place? Why are you motivated to focus on this part of your workflow?*
Finding was to collaborate more is motivating to me because I like working collaboratively and get energy from that interaction but that is missing in my day to day work. I also want to clean up and share my past workflows so that that can create other opportunities for collaboration.
  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::


## Think of a good workflow you’ve seen. What felt good about it? 

With some really nice workflows I have seen they are really organized and easy to understand. I am able to implement them without much trouble and I can find the data that I need easily. The workflows also work well in whatever environment they are being run in not just my computer environment. A really good workflow was for the collaborative R2R papers and Art + Science symposium.

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*For example, what was it about how it was organized, how different people contributed, how it was communicated? Remember meetings are part of workflows too*

There was a lot of opportunity for everyone to provide input. People were excited about the project and their ideas were incorporated. We used tools to track our progress like google forms and google docs. The expectations for different people to contribute were also clear. It was fun and we were able to accomplish a lot more together than we would have been able to accomplish alone. Having group norms is also really helpful
to make sure everyone gets a chance to be heard.
  

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What have you seen or heard about that has you curious? 
I'm curious about the file tracking system that Ileana mentioned for her workflow. I'm also really curious about using GitHub projects for cross team coordination.
::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What are things you’d like to learn or reuse from what you’ve seen? Think from colleagues, talks, and examples online*

 I like when I see that files are easy to find in any computer system. I want an easy way to store and move files. I'd like to have a good way to share data sets that I create publicly.  

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What are some of your values?

I value making a positive impact in the world, learning, and sharing what I know. Sometimes I say my values are family, service, and knowledge.

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.3--->

*Think about something you enjoy doing. What qualities about yourself do you see coming through? What is important to you personally and professionally? How do you want to make people feel?*

I really enjoy brainstorming and building off ideas with other people. I like to think creatively to solve problems and work together to solve more that I could by myself.
  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::

## How do your values show up in your workflow, and how you interact with colleagues?

My values show up in my workflow because I try to include other people in my workflows and figure out how to share what I've learned.

::: {.callout-caution appearance="minimal" icon="false"}


<!---p.3--->

*How do you show up in your daily life at work? For example, being on time, being organized, interacting with people.*

I try to show up in my daily life at work by staying organized, listening, and making sure to give credit to the work of others. I also look for ways 
to make the place I work better than when I found it.

 

 
 

 

  

  

 

  

  

 

 

  

  

 
:::


## What would it look like to connect your values more with your workflow?

It would be great to make my workflows more open and more collaborative. I want to increase the impact of my workflows too.

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.4--->

*Think about that place that seems like a good place to focus. What if you brought what you have seen and want to learn to that place, along with your values? You can draw this*

Bringing what I've seen, want to learn, and my values on the place I want to focus would make a way for me to highlight the work I've done and also make it accessible to others.
The problems we are facing in the world are too big to face alone.

 

  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::
